### ISSUE TITLE
每一天都是 宜嫁娶，正常吗？

### ISSUE THREAD

**Issue by DarkmoonRabbit** [OPN48/pyLunarCalendar#4]
a，想看下哪天适合结婚，但是每天都宜嫁娶

b，出行 嫁娶 开市 祭祀 祈福 动土，这几个重复好像感觉很多，不会是程序写错了吧？

c，还有比如“进人”这个（不止进人一个），我找很久，只有忌进人的日子，好像没有宜进人的日子（找不到），囧

**Comment by cuba3** [comment]
> a，想看下哪天适合结婚，但是每天都宜嫁娶
> 
> b，出行 嫁娶 开市 祭祀 祈福 动土，这几个重复好像感觉很多，不会是程序写错了吧？
> 
> c，还有比如“进人”这个（不止进人一个），我找很久，只有忌进人的日子，好像没有宜进人的日子（找不到），囧

@DarkmoonRabbit 是有这个问题，用了《钦定协纪辨方书卷三》《象吉通书全集》《鳌头通书大全》的内容，这些通书其实看完就会发现，不仅互相不统一，且也存在通书内部互相矛盾的情况，只要把good = {'满': ['嫁娶', '移徙', '求财', '祈福', '祭祀', '出行', '立契', '交易', '开市', '修仓'],
                '成': ['安床', '动土', '移徙', '修造', '嫁娶', '求财', '出行', '栽种', '立契', '竖柱', '安葬', '交易', '开市', '破土'],
                '开': ['安床', '动土', '移徙', '修造', '赴任', '祈福', '宴会', '祭祀', '出行', '求嗣', '入学', '交易', '开市', '竖柱'],
                '建': ['赴任', '祈福', '求嗣', '安葬', '修造', '上樑', '求财', '入学', '嫁娶', '立契', '交涉', '出行'],
                '除': ['祭祀', '祈福', '嫁娶', '出行', '移徙', '动土', '求医', '交易'],
                '平': ['嫁娶', '修造', '破土', '安葬', '开市', '动土', '求嗣'],
                '定': ['祭祀', '祈福', '嫁娶', '修造', '开市', '赴任'],
                '执': ['修造', '装修', '嫁娶', '立契', '祭祀'], '破': ['破土', '求医'],
                '危': ['祭祀', '祈福', '安床', '破土'],
                '收': ['祈福', '求嗣', '赴任', '嫁娶', '修造', '动土', '交易', '立契'],
                '闭': ['祭祀', '祈福', '埋穴', '安葬', '填补']}
        bad = {'建': ['动土', '开仓', '纳采'],
               '平': ['赴任', '移徙', '进人', '嫁娶', '祈福', '动土', '纳采', '修造', '竖柱'],
               '收': ['安床', '移徙', '嫁娶', '安葬', '放债', '动土', '纳采', '开市', '修造', '竖柱', '破土'],
               '闭': ['安床', '手术', '移徙', '求医', '嫁娶', '进人', '出行', '动土', '纳采', '赴任', '开市', '修造', '竖柱', '上梁'],
               '除': ['嫁娶', '赴任', '出行', '立契'], '满': ['安葬', '赴任', '求医'], '定': ['诉讼', '出行', '交涉'],
               '执': ['开市', '求财', '出行', '搬迁'], '破': ['嫁娶', '立契', '交涉', '出行', '搬迁'],
               '危': ['出行', '嫁娶', '安葬', '迁徙'], '成': ['诉讼'], '开': ['放债', '诉讼', '安葬']}

**Comment by cuba3** [comment]
> a，想看下哪天适合结婚，但是每天都宜嫁娶
> 
> b，出行 嫁娶 开市 祭祀 祈福 动土，这几个重复好像感觉很多，不会是程序写错了吧？
> 
> c，还有比如“进人”这个（不止进人一个），我找很久，只有忌进人的日子，好像没有宜进人的日子（找不到），囧

关于这个是因为《钦定协记辩方书》本身就是四库全书之一，主要编纂引用来自《广圣历》、《历例》《枢要历》等，不同通书属于不同时代，有不同指向，部分是 注忌 不从，不注皆可。
等《钦定协记辩方书》神煞等弟模块写完后进行一次翻译吧。

**Comment by DarkmoonRabbit** [comment]
@cuba3 好的，谢谢！我看到有更新了，我看你说：尚未处理宜忌等第表！我等完美的版本出来再下，囧。。。（因为我登录一次github不容易，每次都要验证邮箱才能登录，但是苹果邮箱登录非常麻烦网站打开超级慢、等它打开后登录还得验证手机）

**Comment by cuba3** [comment]
@DarkmoonRabbit > @cuba3 好的，谢谢！我看到有更新了，我看你说：尚未处理宜忌等第表！我等完美的版本出来再下，囧。。。（因为我登录一次github不容易，每次都要验证邮箱才能登录，但是苹果邮箱登录非常麻烦网站打开超级慢、等它打开后登录还得验证手机）

目前《钦定协记辩方书》卷九、卷十、卷十一，卷二十至卷三十一都与此相关，也可以土一点直接把卷二十至卷三十一全部弄进来查表，目前调整计划先用卷十一与卷十作为基础，卷九作为神煞判断依据。这样速度和表大小会少一点，今天已经在做了。

**Comment by DarkmoonRabbit** [comment]
@cuba3 辛苦啦，很期待全新完美版，囧，虽然黄历版本众多，但是我这辈子就信你们这个版的了！因为感觉你们这个有理有据。

**Comment by DarkmoonRabbit** [comment]
@cuba3 啊啊，更新了木有？我刚刚又登录上来github看，好像木有，大神你有wx没？我加你一个方便联系 😄

**Comment by DarkmoonRabbit** [comment]
@cuba3 今早起床看到有更新，周末好(✪▽✪)

**Comment by DarkmoonRabbit** [comment]
@cuba3 我今天下了一个辩方书的pdf版本，看了下你说的那几个章节，感觉好像内容很多！我有什么可以帮助你的吗？我不会py（比如简单重复耗时间的工作）

**Comment by cuba3** [comment]
> @cuba3 我今天下了一个辩方书的pdf版本，看了下你说的那几个章节，感觉好像内容很多！我有什么可以帮助你的吗？我不会py（比如简单重复耗时间的工作）

@DarkmoonRabbit 上周本来已经完成了，更新算法700行……但周天打开电脑居然还原了……可能我git操作失误，就是因为内容太多，第一次花了好几天时间，因为已经写过一次了，今晚会加速完成。

**Comment by DarkmoonRabbit** [comment]
@cuba3 我又花了10分钟登录github
（哭(´;︵;`)）
天啦，看到你的回复真的难受😭，太惨了，写了那么多又恢复如初。。。崩溃了没？哈哈

我想问一下，这次更新后 宜忌方面是不是就完美固定了？因为我现在每天买股票都按照这个来，哈哈，以后我干啥我都要看看这个宜忌
