### ISSUE TITLE
新版出现一个大bug

### ISSUE THREAD

**Issue by DarkmoonRabbit** [OPN48/pyLunarCalendar#5]
@cuba3 
2020年6月16日、18日、30日~~~7月1日.....（后面的没测，应该还有很多）
查看以上日期时候，程序崩溃，爆出错误
`
C:\Users\Administrator\Desktop\pyLunarCalendar-master>python date2LunarData.py
Traceback (most recent call last):
  File "date2LunarData.py", line 39, in <module>
    '神煞宜忌':a.get_AngelDemon(),
  File "C:\Users\Administrator\Desktop\pyLunarCalendar-master\lunar.py", line 743, in get_AngelDemon
    goodBadGodAndThingDic = getTodayGoodBadThing(goodBadGodAndThingDic)
  File "C:\Users\Administrator\Desktop\pyLunarCalendar-master\lunar.py", line 737, in getTodayGoodBadThing
    dic[badThingKey] += godItem[4]
IndexError: tuple index out of range
`

**Comment by cuba3** [comment]
@DarkmoonRabbit > @cuba3
> 2020年6月16日、18日、30日~~~7月1日.....（后面的没测，应该还有很多）
> 查看以上日期时候，程序崩溃，爆出错误
> `C:\Users\Administrator\Desktop\pyLunarCalendar-master>python date2LunarData.py Traceback (most recent call last): File "date2LunarData.py", line 39, in <module> '神煞宜忌':a.get_AngelDemon(), File "C:\Users\Administrator\Desktop\pyLunarCalendar-master\lunar.py", line 743, in get_AngelDemon goodBadGodAndThingDic = getTodayGoodBadThing(goodBadGodAndThingDic) File "C:\Users\Administrator\Desktop\pyLunarCalendar-master\lunar.py", line 737, in getTodayGoodBadThing dic[badThingKey] += godItem[4] IndexError: tuple index out of range`

我知道这个问题，调试阶段，之后修好，原来设计只考虑凶神掌凶，吉神掌吉，后来发现凶神也掌吉，今天修复。怕代码丢失，提的比较频繁……我之后会新开一个开发者分支，保证master分支稳定

**Comment by DarkmoonRabbit** [comment]
@cuba3 师傅，你能给我个你的微信联系方式吗~？囧，我有很多事情想和您交流，我每次登录github太难了。。。

**Comment by cuba3** [comment]
> @cuba3 师傅，你能给我个你的微信联系方式吗~？囧，我有很多事情想和您交流，我每次登录github太难了。。。

wx：guobaidu

**Comment by DarkmoonRabbit** [comment]
@cuba3 OK 我加你了！终于找到组织了！！！！
