### ISSUE TITLE
2020年6月20日对应的农历结果是五月初三？难道不是四月二十九吗？

### ISSUE THREAD

**Issue by yuzishui** [OPN48/pyLunarCalendar#7]
请看转换结果。

{"日期": "2020-06-20 23:30:00", "农历数字": [2020, 5, 3, ""], "农历": "二零二零 庚子[鼠]年 五月小初三", "星期": "星期六", "今日节日": ["", "", ""], "八字": "庚子 壬午 乙未 丙子", "今日节气": "无", "下一节气": ["夏至", [6, 21], 2020], "今年节气表": {"小寒": [1, 6], "大寒": [1, 20], "立春": [2, 4], "雨水": [2, 19], "惊蛰": [3, 5], "春分": [3, 20], "清明": [4, 4], "谷雨": [4, 19], "立夏": [5, 5], "小满": [5, 20], "芒种": [6, 5], "夏至": [6, 21], "小暑": [7, 6], "大暑": [7, 22], "立秋": [8, 7], "处暑": [8, 22], "白露": [9, 7], "秋分": [9, 22], "寒露": [10, 8], "霜降": [10, 23], "立冬": [11, 7], "小雪": [11, 22], "大雪": [12, 7], "冬至": [12, 21]}, "季节": "仲夏", "今日时辰": ["丙子", "丁丑", "戊寅", "己卯", "庚辰", "辛巳", "壬午", "癸未", "甲申", "乙酉", "丙戌", "丁亥", "戊子"], "时辰凶吉": ["凶", "凶", "吉", "吉", "凶", "吉", "凶", "凶", "吉", "凶", "吉", "吉", "吉"], "生肖冲煞": "羊日冲牛", "星座": "双子座", "星次": "鹑首", "彭祖百忌": "乙不栽植 千株不长,未不服药 毒气入肠", "彭祖百忌精简": "乙不栽植
未不服药", "十二神": ["除", "勾陈", "黄道日"], "廿八宿": "胃土雉", "今日三合": ["猪", "兔"], "今日六合": "马", "今日五行": ["天干", "乙", "属木", "地支", "未", "属土", "纳音", "金", "属金", "廿八宿", "胃", "宿", "十二神", "除", "日"], "纳音": "砂中金", "九宫飞星": "957813462", "吉神方位": ["喜神西北", "财神东北", "福神西南", "阳贵西南", "阴贵正北"], "今日胎神": "碓磨厕房内北", "神煞宜忌": [[["岁德合", "六合", "不将", "不守塚", "吉期", "兵宝"], ["勾陈", "三娘煞", "四离", "制日"]], [["结婚姻", "沐浴", "剃头", "修造", "上官", "进人口", "经络", "纳财", "扫舍宇", "破土", "安葬", "选将", "纳畜", "赴任", "宴会", "整手足甲", "安抚边境", "立券交易", "入宅", "出师", "施恩", "整容", "搬移", "酝酿", "解除", "举正直", "纳采", "临政"], ["栽种"]]], "今日吉神": ["岁德合", "六合", "不将", "不守塚", "吉期", "兵宝"], "今日凶煞": ["勾陈", "三娘煞", "四离", "制日"], "宜": ["结婚姻", "沐浴", "剃头", "修造", "上官", "进人口", "经络", "纳财", "扫舍宇", "破土", "安葬", "选将", "纳畜", "赴任", "宴会", "整手足甲", "安抚边境", "立券交易", "入宅", "出师", "施恩", "整容", "搬移", "酝酿", "解除", "举正直", "纳采", "临政"], "忌": ["栽种"], "时辰经络": "胆"}

**Comment by DarkmoonRabbit** [comment]
我这边是最新的版本，是2020-4-29（闰）

**Comment by cuba3** [comment]
八字月柱与八字日柱算神煞版本
日期 	:	 2020-06-20 22:30:00
农历数字 :	 (2020, 4, 29, '闰')
农历 	:	 二零二零 庚子[鼠]年 闰四月小廿九
星期 	:	 星期六
今日节日 :	 ('', '', '')
八字 	:	 庚子 壬午 甲午 乙亥
今日节气 :	 无
下一节气 :	 ('夏至', (6, 21), 2020)
今年节气表 :	 {'小寒': (1, 6), '大寒': (1, 20), '立春': (2, 4), '雨水': (2, 19), '惊蛰': (3, 5), '春分': (3, 20), '清明': (4, 4), '谷雨': (4, 19), '立夏': (5, 5), '小满': (5, 20), '芒种': (6, 5), '夏至': (6, 21), '小暑': (7, 6), '大暑': (7, 22), '立秋': (8, 7), '处暑': (8, 22), '白露': (9, 7), '秋分': (9, 22), '寒露': (10, 8), '霜降': (10, 23), '立冬': (11, 7), '小雪': (11, 22), '大雪': (12, 7), '冬至': (12, 21)}
季节 	:	 仲夏
今日时辰 :	 ['甲子', '乙丑', '丙寅', '丁卯', '戊辰', '己巳', '庚午', '辛未', '壬申', '癸酉', '甲戌', '乙亥', '丙子']
时辰凶吉 :	 ['吉', '吉', '凶', '吉', '凶', '凶', '吉', '凶', '吉', '吉', '凶', '凶', '凶']
生肖冲煞 :	 马日冲鼠
星座 	:	 双子座
星次 	:	 鹑首
彭祖百忌 :	 甲不开仓 财物耗散,午不苫盖 屋主更张
彭祖百忌精简 :	 甲不开仓<br>午不苫盖
十二神 	:	 ('建', '司命', '黑道日')
廿八宿 	:	 胃土雉
今日三合 :	 ['狗', '虎']
今日六合 :	 羊
今日五行 :	 ['天干', '甲', '属木', '地支', '午', '属火', '纳音', '金', '属金', '廿八宿', '胃', '宿', '十二神', '建', '日']
纳音 	:	 砂中金
九宫飞星 :	 957813462
吉神方位 :	 ['喜神东北', '财神东北', '福神正北', '阳贵西南', '阴贵东北']
今日胎神 :	 占门碓房内北
神煞宜忌 :	 ((['三合', '鸣吠对', '不守塚', '官日', '天赦', '天愿', '天官', '金堂', '小时', '兵福'], ['岁破', '月建', '月刑', '月厌', '天瘟', '地火', '四离', '月建转杀', '土符', '土府', '宝日']), (['诸事不宜'], ['诸事不宜']))
今日吉神 :	 ['三合', '鸣吠对', '不守塚', '官日', '天赦', '天愿', '天官', '金堂', '小时', '兵福']
今日凶煞 :	 ['岁破', '月建', '月刑', '月厌', '天瘟', '地火', '四离', '月建转杀', '土符', '土府', '宝日']
宜 		:	 ['诸事不宜']
忌 		:	 ['诸事不宜']
时辰经络 :	 三焦

**Comment by cuba3** [comment]
请使用git fetch命令 @yuzishui

**Comment by yuzishui** [comment]
谢谢
