### ISSUE TITLE
每日宜忌的算法问题

### ISSUE THREAD

**Issue by sinacn546** [OPN48/pyLunarCalendar#8]
作者程序的结果：
农历：二零二零 庚子[鼠]年 冬月小廿五
宜：['诸事不宜']
忌：['诸事不宜']

但在别的平台查询的结果大多是：
宜：祭祀、冠笄、嫁娶、会友、认养、裁衣、结网
忌：造庙、移徙、入宅、作灶、安葬

请问是算法不同的原因导致的吗？

**Comment by cuba3** [comment]
> 作者程序的结果：
> 农历：二零二零 庚子[鼠]年 冬月小廿五
> 宜：['诸事不宜']
> 忌：['诸事不宜']
> 
> 但在别的平台查询的结果大多是：
> 宜：祭祀、冠笄、嫁娶、会友、认养、裁衣、结网
> 忌：造庙、移徙、入宅、作灶、安葬
> 
> 请问是算法不同的原因导致的吗？

用的是《钦定协纪辨方书》的算法，本来宜忌的科学部分就是为了把红白喜事分出来（不让红事白事在同一天），不同地方有不同的算法，很多别的平台都是查表法，毕竟在通书里面的宜忌并没有作灶、造庙，框架已经搭好了，你要是有什么通书觉得比较准确，可以发过来，既有框架换算法不是问题。

**Comment by sinacn546** [comment]
学习了，谢谢
